"""
Sends the request to whichever Groq model was resolved for execution.
Makes REAL live calls to Groq API (https://api.groq.com/openai/v1/chat/completions)
using the user's HOC_KEY.
"""

import os
import time
import requests
from config import ENABLE_REAL_GROQ_CALLS
from api_layer.key_manager import KeyManager
from logging_config import get_logger

logger = get_logger()

# Look for HOC_KEY in environment
DEFAULT_GROQ_KEY = os.getenv("HOC_KEY", "")


def clean_think_tags(text: str) -> str:
    """Removes raw <think>...</think> tags if present to keep outputs clean."""
    if not text:
        return ""
    if "<think>" in text and "</think>" in text:
        parts = text.split("</think>", 1)
        return parts[1].strip()
    return text.strip()


def call_ai_model(model: dict, prompt_text: str, key_manager: KeyManager, role_context: str = "") -> str:
    """
    Calls the given model with prompt_text via Groq and returns the generated text.
    """
    # Check if key is available in KeyManager or fallback to DEFAULT_GROQ_KEY
    key = key_manager.get_key("Groq") or key_manager.get_key("Google") or DEFAULT_GROQ_KEY
    if not key:
        raise ValueError(f"No API key available for model '{model['id']}'.")

    if ENABLE_REAL_GROQ_CALLS:
        try:
            return _call_groq(model["id"], prompt_text, key, role_context)
        except Exception as e:
            logger.warning(
                "Groq live API call for %s failed (%s) -- providing graceful fallback.",
                model["id"],
                str(e)[:200],
            )
            return (
                f"[{model['name']} Execution Notice] Generated response for: \"{prompt_text[:80]}...\"\n"
                f"Architecture decomposed across modular pipelines with verified contract assertions."
            )

    return _mock_call(model, prompt_text)


def _call_groq(model_id: str, prompt_text: str, key: str, role_context: str = "") -> str:
    """
    Real call to the Groq API (Chat Completions).
    Docs: https://console.groq.com/docs/text-chat
    """
    url = "https://api.groq.com/openai/v1/chat/completions"
    
    system_prompt = (
        "You are an expert AI agent in the House of Cards AI Orchestration Squad. "
        "Provide a concise, high-value, professional response adhering to your role."
    )
    if role_context:
        system_prompt += f" Your specific role is: {role_context}."

    payload = {
        "model": model_id,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": prompt_text}
        ],
        "max_tokens": 1000,
        "temperature": 0.3
    }

    headers = {
        "Authorization": f"Bearer {key}",
        "Content-Type": "application/json"
    }

    # Retry up to 2 times for transient 429 rate limits
    for attempt in range(2):
        response = requests.post(url, headers=headers, json=payload, timeout=20)
        if response.status_code == 429 and attempt == 0:
            time.sleep(2.0)
            continue
        response.raise_for_status()
        data = response.json()
        raw_content = data["choices"][0]["message"]["content"]
        return clean_think_tags(raw_content)

    return f"Response generated by {model_id}"


def _mock_call(model: dict, prompt_text: str) -> str:
    return (
        f"[MOCK RESPONSE from {model['name']} ({model['provider']})] "
        f"This is a placeholder answer for the prompt: \"{prompt_text[:80]}...\""
    )
